### ISSUE TITLE
How to support other LLM Models ?  for example: Vicuna-13b  Chatglm-6B

### ISSUE THREAD

**Issue by SniperM99** [ricklamers/gpt-code-ui#45] opened 2023-07-13 02:53 UTC
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

How to support other LLM Models ?  

for example: Vicuna-13b  Chatglm-6B, nwo i am tuning glm-6b.
But i wish use auto-code by local LLM（glm-6b）, it similar GPT4 Code Interpreter function。

### ✔️ Solution

How to support other LLM Models ?  

for example: Vicuna-13b  Chatglm-6B, nwo i am tuning glm-6b.
But i wish use auto-code by local LLM（glm-6b）, it similar GPT4 Code Interpreter function。

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ricklamers** [comment] 2023-07-13 08:07
Would welcome a PR for this 👍🏻

Duplicate of https://github.com/ricklamers/gpt-code-ui/discussions/18

**Closed by ricklamers** 2023-07-13 08:07 UTC
Labels: enhancement
