### ISSUE TITLE
OpenAI API generated code depends on automatic installation

### ISSUE THREAD

**Issue by soulteary** [ricklamers/gpt-code-ui#62] opened 2023-07-24 09:40 UTC
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

After the code is generated by the OpenAI API, if there is no local dependency on Python or other languages, it will be automatically installed.

### ✔️ Solution

You only need to make some simple adjustments to the code, use pre-script or monitor whether it is an execution error due to lack of dependencies during execution, install it, and try again.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ricklamers** [comment] 2023-07-25 09:51
Agree this would be cool to add.

Duplicate of https://github.com/ricklamers/gpt-code-ui/discussions/6

**Closed by ricklamers** 2023-07-25 09:51 UTC
Labels: enhancement
