### ISSUE TITLE
Azure OpenAI Support

### ISSUE THREAD

**Issue by master117** [ricklamers/gpt-code-ui#23] opened 2023-05-24 17:07 UTC
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/ricklamers/gpt-code-ui/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/ricklamers/gpt-code-ui/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Hi, is there any plans to support Azure OpenAI, as it is the preferred solution by most companies to keep their data separated from OpenAI.

### ✔️ Solution

Add support for Azure OpenAI

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ricklamers** [comment] 2023-05-24 17:08
Duplicate of https://github.com/ricklamers/gpt-code-ui/issues/5

**Closed by ricklamers** 2023-05-24 17:08 UTC
Labels: enhancement
