### ISSUE TITLE
It can not install dependency automatically. 

### ISSUE THREAD

**Issue by parthvadhadiya** [ricklamers/gpt-code-ui#46] opened 2023-07-14 07:02 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/ricklamers/gpt-code-ui/labels/bug) didn't find any similar reports.

### Expected Behavior

It should potentially detect pip or pip3 command and try to install that as dependency on kernal. 

### Current behaviour

I have upload a file and asked to read top 2 line from the file. 
code it produce seems correct
```
import pandas as pd

# Read the uploaded file
data = pd.read_excel('roiCalculate.xlsx')

# Extract the top 2 lines
top_2_lines = data.head(2)

# Print the top 2 lines
print(top_2_lines)
```
It throws error 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 import pandas as pd
      3 # Read the uploaded file
      4 data = pd.read_excel('roiCalculate.xlsx')

ModuleNotFoundError: No module named 'pandas'

### Steps to reproduce

pip3 install gpt-code-ui
gptcode

got to chatbot
upload excel file or csv file

write in chat 
"What are the top 2 line in uploaded file"

### Possible solution

if it is ipython then I think adding ! in prefix to pip3 will work well. otherwise, we need to find a way to run dependency. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Programming Version

python3

### gpt-code-ui Version

 v0.42.32

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of gpt-code-ui.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ricklamers** [comment] 2023-07-14 09:39
Agreed!

Duplicate of https://github.com/ricklamers/gpt-code-ui/discussions/6

**Closed by ricklamers** 2023-07-14 09:39 UTC
Labels: bug
